version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    environment: 
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=ghaza
     - POSTGRES_DB=CatalogDb
    restart: always
    ports:
     - "5432:5432"
    volumes:
     - postgres_catalog:/var/lib/postgresql/data/

  adminer:
    image: adminer
    container_name: my_adminer
    ports:
      - "8080:8080"
    depends_on:
      - catalogdb
